import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { collection, doc, getDoc } from 'firebase/firestore';
import { db } from '../../utils/firebase-config';

export default function Home() {
  const router = useRouter();
  const { id } = router.query;
  const [user, setUser] = useState(null);

  const fetchData = async () => {
    try {
      const docRef = doc(db, 'households', id);
      const docSnap = await getDoc(docRef);
      const data = docSnap.data();
      setUser(data);
    } catch (error) {}
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div>
      <Head>
        <title>Next PWA Demo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {user !== null && (
          <ul>
            <li>Name: {user.name}</li>
            <li>Email: {user.email}</li>
            <li>Phone: {user.phone}</li>
            <li>Address: {user.address}</li>
            <li>Country: {user.country}</li>
          </ul>
        )}
      </main>
    </div>
  );
}
