import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';
import { collection, getDocs } from 'firebase/firestore';
import { db } from '../utils/firebase-config';

export default function Home() {
  const householdsRef = collection(db, 'households');
  const [users, setUsers] = useState([]);

  const fetchData = async () => {
    try {
      const data = await getDocs(householdsRef);
      const newData = data.docs.map((doc) => ({ ...doc.data(), id: doc.id }));
      setUsers(newData);
      console.log(newData);
    } catch (error) {}
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div>
      <Head>
        <title>Next PWA Demo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <table className={styles.table}>
          <tr className={styles.tr}>
            <th className={styles.th}>Name</th>
            <th className={styles.th}>Phone</th>
            <th className={styles.th}>Email</th>
            <th>Actions</th>
          </tr>
          {users.map((user) => (
            <tr className={styles.tr} key={user.id}>
              <td className={styles.th}>{user.name}</td>
              <td className={styles.th}>{user.phone}</td>
              <td className={styles.th}>{user.email}</td>
              <td className={styles.th}>
                <Link href={'household/' + user.id}>
                  <a>VIEW</a>
                </Link>
              </td>
            </tr>
          ))}
        </table>
      </main>
    </div>
  );
}
